orbs:
  react: thefrontside/react@0.2.0
version: 2.1

jobs:
  deploy-job:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  push:
    jobs:
      - react/install
      - react/test:
          requires:
            - react/install
      - react/build:
          requires:
            - react/install
  deploy:
    jobs:
      - deploy-job:
          requires:
            - react/build
          filters:
            branches:
              only: master
