orbs:
  react: thefrontside/react@0.2.0
version: 2.1

jobs:
  deploy-job:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: build
          command: npm run build
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

workflows:
  push:
    jobs:
      - react/install
          filters:
            branches:
              ignore: master
      - react/test:
          requires:
            - react/install
          filters:
            branches:
              ignore: master
      - react/build:
          requires:
            - react/install
          filters:
            branches:
              ignore: master
      - deploy-job:
          filters:
            branches:
              only: master

